[package]
name = "classifier-in-rust"
version = "0.1.0"
authors = ["Vlad Orlov"]
edition = "2018"

[dependencies]
smartcore = { version = "0.2.0", features=["nalgebra-bindings", "datasets"]}
nalgebra = { version="0.23.0", features = ["serde-serialize"]}
argmin = "0.3.1"
