[package]
name = "meet-smartcore"
version = "0.1.0"
authors = ["Vlad Orlov"]
edition = "2018"

[dependencies]
smartcore = { version = "0.2.0", features=["nalgebra-bindings", "ndarray-bindings", "datasets"]}
nalgebra = "0.23.0"
ndarray = "0.14.0"
serde = "1.0.115"
bincode = "1.3.1"
